function E_current = compute_energy(x, params)
%COMPUTE_ENERGY
%    E_current = COMPUTE_ENERGY(X1,X2,X3,X4,X5,X6,U,MC,M1,M2,J1,J2,l1,l2,L1,L2,CC,C1,C2,G)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    08-Apr-2026 21:38:10

% unpack params
mc = params.mc;
m1 = params.m1;
m2 = params.m2;
L1 = params.L1;
L2 = params.L2;
l1 = params.l1;
l2 = params.l2;
J1 = params.J1;
J2 = params.J2;
cc = params.cc;
c1 = params.c1;
c2 = params.c2;
g = params.g;

% unpack states
x1 = x(1);
x2 = x(2);
x3 = x(3);
x4 = x(4);
x5 = x(5);
x6 = x(6);

E_current = (m2.*(l2.^2.*x6.^2+x2.^2+L1.^2.*x4.^2-L1.*x2.*x4.*cos(x3).*2.0-l2.*x2.*x6.*cos(x5).*2.0+L1.*l2.*x4.*x6.*cos(x3-x5).*2.0))./2.0+(J1.*x4.^2)./2.0+(J2.*x6.^2)./2.0+g.*(m2.*(L1.*cos(x3)+l2.*cos(x5))+l1.*m1.*cos(x3))+(m1.*(l1.^2.*x4.^2+x2.^2-l1.*x2.*x4.*cos(x3).*2.0))./2.0+(mc.*x2.^2)./2.0;
end
